# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {C:/Users/user/Desktop/extension/Final vivado/extension.cache/wt} [current_project]
set_property parent.project_path {C:/Users/user/Desktop/extension/Final vivado/extension.xpr} [current_project]
set_property XPM_LIBRARIES XPM_CDC [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
add_files -quiet {{C:/Users/user/Desktop/Final link/Final vivado/FinalProject.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.dcp}}
set_property used_in_implementation false [get_files {{C:/Users/user/Desktop/Final link/Final vivado/FinalProject.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.dcp}}]
read_verilog -library xil_defaultlib {
  {C:/Users/user/Desktop/extension/Final vivado/src/don't touch/ssDisplayer.v}
  {C:/Users/user/Desktop/extension/Final vivado/src/don't touch/ssDecoder.v}
  {C:/Users/user/Desktop/extension/Final vivado/src/don't touch/lib.v}
  {C:/Users/user/Desktop/extension/Final vivado/src/don't touch/SevenSegment.v}
  {C:/Users/user/Desktop/extension/Final vivado/src/don't touch/Timer.v}
  {C:/Users/user/Desktop/extension/Final vivado/src/DisplayController.v}
  {C:/Users/user/Desktop/extension/Final vivado/src/don't touch/VGADisplayer.v}
  {C:/Users/user/Desktop/extension/Final vivado/src/MP_TimerController.v}
  {C:/Users/user/Desktop/extension/Final vivado/src/don't touch/ButtonFSM.v}
  {C:/Users/user/Desktop/extension/Final vivado/src/TrafficLight.v}
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc {{C:/Users/user/Desktop/extension/Final vivado/src/don't touch/PortDefine_basys3.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/user/Desktop/extension/Final vivado/src/don't touch/PortDefine_basys3.xdc}}]


synth_design -top TrafficLight -part xc7a35tcpg236-1


write_checkpoint -force -noxdef TrafficLight.dcp

catch { report_utilization -file TrafficLight_utilization_synth.rpt -pb TrafficLight_utilization_synth.pb }
